### ISSUE TITLE
PHP notice just after adding a new block

### ISSUE THREAD

**Issue by mudrd8mz** [antoni-oliver/graderanking#1]
It seems the plugin does not handle well the case where there are no grade categories defined yet:

![image](https://user-images.githubusercontent.com/85831/129195944-79991ef9-ea1a-460e-81f7-ed99388db1cf.png)

However, even after adding a category, a bung of other notices appears:

![image](https://user-images.githubusercontent.com/85831/129196383-67534fc9-05fc-457c-b810-cab7453c3d31.png)

Have you tested the plugin with developer debugging enabled?

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Functionality

**Comment by antoni-oliver** [comment]
Fixed in d70ae3c6ef9b0e0eb1979e2bec19325b811d876e.
