### ISSUE TITLE
Warnings on undefined constants

### ISSUE THREAD

**Issue by mudrd8mz** [antoni-oliver/graderanking#3]
I am seeing warnings like

Warning: Use of undefined constant GRADE_TYPE_VALUE - assumed 'GRADE_TYPE_VALUE' (this will throw an Error in a future version of PHP) in /home/mudrd8mz/www/mdk/m311/moodle/lib/grade/grade_object.php on line 182

Warning: Use of undefined constant GRADE_DISPLAY_TYPE_DEFAULT - assumed 'GRADE_DISPLAY_TYPE_DEFAULT' (this will throw an Error in a future version of PHP) in /home/mudrd8mz/www/mdk/m311/moodle/lib/grade/grade_object.php on line 182

after having the block installed

**Comment by antoni-oliver** [comment]
This is because this plugin uses that library from core Moodle.

If there are warnings related to this, they are caused by that core Moodle library and not by this plugin.
