### ISSUE TITLE
user firstname lastname should not be rendered manually

### ISSUE THREAD

**Issue by danmarsden** [antoni-oliver/graderanking#9]
please use the Moodle api function "fullname() to display the name of a user - some langagues will display them in a different order - some sites will configure the display name in different ways too.
https://github.com/antoni-oliver/graderanking/blob/main/block_graderanking.php#L129

**Comment by antoni-oliver** [comment]
Fixed in f2de85fc28f6da860332a7cc80c631e6c140c9d2.

Thank you.
